# -*- coding: utf-8 -*-
"""Cognitive Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16ay14mtz6OHkqdsX6Zd8PdIla2dSgd_b
"""

import pandas as pd
import numpy as np
from sklearn.model_selection import LeaveOneOut, cross_val_predict
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier

df = pd.read_csv('pone.0203629.s002.csv', index_col=0)

feature_cols = [
    'pcpd',
    'bpcpd',
    'msrt',
    'amp',
    'slos',
    'corr',
    'tlx',
    'mag',
    'ints'
]

X = df[feature_cols].copy()


target_mapping = {
    'EASY': 0,
    'CONTROL': 1,
    'DIFF': 2
}
y = df['ttype'].map(target_mapping).astype(int)


participant_ids = df['subj'].values


scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

print(f"Data ready: X shape {X_scaled.shape}, Y shape {y.shape}")
print(f"Features used: {len(feature_cols)} | Target classes: {y.nunique()}")

if 'X_scaled' not in locals():
    raise ValueError("Run Block 1 (Preprocessing) first.")

print("\n--- Training Random Forest Model with Leave-One-Subject-Out Cross-Validation ---")


loso = LeaveOneOut()
groups = participant_ids


rf_model = RandomForestClassifier(
    n_estimators=300,
    max_depth=8,
    random_state=42,
    class_weight='balanced'
)

y_pred_loso = cross_val_predict(rf_model, X_scaled, y, cv=loso.split(X_scaled, y, groups=groups))

print(f"Total predictions generated via LOSO: {len(y_pred_loso)}")
print("LOSO Cross-Validation Complete.")

import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import accuracy_score, f1_score, confusion_matrix, classification_report

if 'y_pred_loso' not in locals():
    raise ValueError("Run Block 2 (Random Forest) first.")

class_labels = ['Low (EASY)', 'Medium (CONTROL)', 'High (DIFF)']

print("\n" + "="*70)
print("1. Subject-Independent Classification Performance (LOSO)")
print("="*70)

accuracy = accuracy_score(y, y_pred_loso)
macro_f1 = f1_score(y, y_pred_loso, average='macro')
weighted_f1 = f1_score(y, y_pred_loso, average='weighted')

print(f"Overall Accuracy: {accuracy:.4f}")
print(f"Macro F1-Score (Unweighted Average): {macro_f1:.4f} \u2b50")
print(f"Weighted F1-Score: {weighted_f1:.4f}")

print("\nDetailed Classification Report:")
print(classification_report(y, y_pred_loso, target_names=class_labels))

cm = confusion_matrix(y, y_pred_loso)
plt.figure(figsize=(7, 6))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=class_labels, yticklabels=class_labels)
plt.title('Confusion Matrix (Subject-Independent LOSO)')
plt.ylabel('True Task Type')
plt.xlabel('Predicted Task Type')
plt.show()

print("\n" + "="*70)
print("2. Random Forest Feature Importance")
print("="*70)

final_rf_model = RandomForestClassifier(n_estimators=300, max_depth=8, random_state=42, class_weight='balanced')
final_rf_model.fit(X_scaled, y)

importances = final_rf_model.feature_importances_
feature_importance_df = pd.DataFrame({
    'Feature': X.columns,
    'Importance': importances
}).sort_values(by='Importance', ascending=False)

print(feature_importance_df)


plt.figure(figsize=(9, 6))
sns.barplot(x='Importance', y='Feature', data=feature_importance_df, palette='viridis')
plt.title('Feature Importance for Cognitive Load Classification')
plt.xlabel('Importance Score')
plt.ylabel('Feature')
plt.tight_layout()
plt.show()